-- questao 2
CREATE TABLE Automovel(placa CHAR(7),	marca VARCHAR(20),modelo VARCHAR(20),ano INTEGER);

CREATE TABLE Segurado(cpf CHAR(11), nome VARCHAR(40), telefone VARCHAR(15), endereco VARCHAR(40));

CREATE TABLE Perito(cpf CHAR(11), nome VARCHAR(40), telefone VARCHAR(15), endereco VARCHAR(40));

CREATE TABLE Oficina(id SERIAL);

CREATE TABLE Seguro(id SERIAL, data_inicio DATE, data_fim DATE);

CREATE TABLE Sinistro(id SERIAL, data DATE);

CREATE TABLE Pericia(id SERIAL, resultado TEXT);

CREATE TABLE Reparo(id SERIAL);

----------- fim questao 2 ----------------

--=============--=========--============--========

----------- questao 3 ----------------
ALTER TABLE Automovel ADD CONSTRAINT Automovel_pkey PRIMARY KEY (placa);

ALTER TABLE Segurado ADD CONSTRAINT Segurado_pkey PRIMARY KEY (cpf);

ALTER TABLE PERITO ADD CONSTRAINT PERITO_PKEY PRIMARY KEY (cpf);

ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_PKEY PRIMARY KEY (id);

ALTER TABLE SEGURO ADD CONSTRAINT SEGURO_PKEY PRIMARY KEY (id);

ALTER TABLE SINISTRO ADD CONSTRAINT SINISTRO_PKEY PRIMARY KEY (id);

ALTER TABLE PERICIA ADD CONSTRAINT PERICIA_PKEY PRIMARY KEY (id);

ALTER TABLE REPARO ADD CONSTRAINT REPARO_PKEY PRIMARY KEY (id);
----------- fim questao 3 ----------------

--===========================================================

----------- questao 4 --------------------
ALTER TABLE OFICINA ADD COLUMN reparos_feitos INTEGER;
ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_REPAROS_FEITOS_FKEY FOREIGN KEY (reparos_feitos) REFERENCES REPARO(id);

ALTER TABLE OFICINA ADD COLUMN reparos_agendados INTEGER;
ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_REPAROS_AGENDADOS_FKEY FOREIGN KEY (reparos_agendados) REFERENCES REPARO(id);

ALTER TABLE SEGURO ADD COLUMN automovel CHARACTER(7);
ALTER TABLE SEGURO ADD COLUMN segurado CHARACTER(11);
ALTER TABLE SEGURO ADD COLUMN tipo_seguro TEXT;

ALTER TABLE SEGURO ADD CONSTRAINT SEGURO_AUTOMOVEL_FKEY FOREIGN KEY (automovel) REFERENCES AUTOMOVEL(placa);
ALTER TABLE SEGURO ADD CONSTRAINT SEGURO_SEGURADO_FKEY FOREIGN KEY (segurado) REFERENCES SEGURADO(cpf);

ALTER TABLE SINISTRO ADD COLUMN automovel CHARACTER(7);
ALTER TABLE SINISTRO ADD COLUMN segurado CHARACTER(11);

ALTER TABLE SINISTRO ADD CONSTRAINT SINISTRO_AUTOMOVEL_FKEY FOREIGN KEY (automovel) REFERENCES AUTOMOVEL(placa);
ALTER TABLE SINISTRO ADD CONSTRAINT SINISTRO_SEGURADO_FKEY FOREIGN KEY (segurado) REFERENCES SEGURADO(cpf);

ALTER TABLE PERICIA ADD COLUMN perito CHARACTER(11);
ALTER TABLE PERICIA ADD COLUMN causa INTEGER;

ALTER TABLE PERICIA ADD CONSTRAINT PERICIA_PERITO_FKEY FOREIGN KEY (perito) REFERENCES PERITO(cpf);
ALTER TABLE PERICIA ADD CONSTRAINT PERICIA_SINISTRO_FKEY FOREIGN KEY (causa) REFERENCES SINISTRO(id);

ALTER TABLE REPARO ADD COLUMN pericia INTEGER;
ALTER TABLE REPARO ADD COLUMN oficina INTEGER;

ALTER TABLE REPARO ADD CONSTRAINT REPARO_PERICIA_FKEY FOREIGN KEY (pericia) REFERENCES PERICIA(id);
ALTER TABLE REPARO ADD CONSTRAINT REPARO_OFICINA_FKEY FOREIGN KEY (oficina) REFERENCES OFICINA(id);
----------- fim questao 4 ----------------

----------- questao 6 -----------------
DROP TABLE REPARO CASCADE;
DROP TABLE PERICIA;
DROP TABLE SINISTRO;
DROP TABLE SEGURO;
DROP TABLE OFICINA;
DROP TABLE AUTOMOVEL;
DROP TABLE SEGURADO;
DROP TABLE PERITO;
----------- fim questao 6 -----------

----------- QUESTAO 7 -------------
CREATE TABLE Automovel(placa CHAR(7),	marca VARCHAR(20) NOT NULL,modelo VARCHAR(20) NOT NULL,ano INTEGER NOT NULL, CONSTRAINT AUTOMOVEL_PKEY PRIMARY KEY (placa));

CREATE TABLE Segurado(cpf CHAR(11), nome VARCHAR(40) NOT NULL,telefone VARCHAR(15) NOT NULL, endereco VARCHAR (40) NOT NULL, CONSTRAINT SEGURADO_PKEY PRIMARY KEY (cpf));

CREATE TABLE Perito(cpf CHAR(11), nome VARCHAR(40) NOT NULL, telefone VARCHAR(15) NOT NULL, endereco VARCHAR(40) NOT NULL, CONSTRAINT PERITO_PKEY PRIMARY KEY (cpf));

CREATE TABLE Oficina(id SERIAL,	reparos_agendados INTEGER, reparos_feitos INTEGER, CONSTRAINT OFICINA_PKEY PRIMARY KEY (id));

CREATE TABLE Seguro(id SERIAL, data_inicio DATE NOT NULL, data_fim DATE NOT NULL,	tipo_seguro TEXT NOT NULL,segurado CHARACTER(11),	automovel CHARACTER(7),	CONSTRAINT SEGURO_PKEY PRIMARY KEY (id),	CONSTRAINT SEGURO_AUTOMOVEL_FKEY FOREIGN KEY (automovel) REFERENCES AUTOMOVEL(placa) ON DELETE CASCADE, CONSTRAINT SEGURO_SEGURADO_FKEY FOREIGN KEY (segurado) REFERENCES SEGURADO(cpf) ON DELETE CASCADE);

CREATE TABLE Sinistro(id SERIAL, data DATE NOT NULL,	seguro INTEGER NOT NULL,CONSTRAINT SINISTRO_PEKY PRIMARY KEY (id), CONSTRAINT SINISTRO_SEGURO_FKEY FOREIGN KEY (seguro) REFERENCES SEGURO(id) ON DELETE CASCADE);

CREATE TABLE Pericia(id SERIAL, resultado TEXT NOT NULL,perito CHARACTER(11) NOT NULL,causa INTEGER NOT NULL,CONSTRAINT PERICIA_PKEY PRIMARY KEY (id),CONSTRAINT PERICIA_PERITO_FKEY FOREIGN KEY (perito) REFERENCES PERITO(cpf) ON DELETE CASCADE, CONSTRAINT PERICIA_CAUSA_FKEY FOREIGN KEY (causa) REFERENCES SINISTRO(id)ON DELETE CASCADE);

CREATE TABLE Reparo(id SERIAL,pericia INTEGER NOT NULL,oficina INTEGER NOT NULL,CONSTRAINT REPARO_PKEY PRIMARY KEY (id),CONSTRAINT REPARO_PERICIA_FKEY FOREIGN KEY (pericia) REFERENCES PERICIA(id) ON DELETE CASCADE,CONSTRAINT REPARO_OFICINA_FKEY FOREIGN KEY (oficina) REFERENCES OFICINA(id) ON DELETE CASCADE);

ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_REPAROS_FEITOS_FKEY FOREIGN KEY (reparos_feitos) REFERENCES REPARO(id) ON DELETE CASCADE; 
ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_REPAROS_AGENDADOS_FKEY FOREIGN KEY (reparos_agendados) REFERENCES REPARO(id) ON DELETE CASCADE;

----------- FIM QUESTAO 7 -----------

------------- QUESTAO 9 -------------
DROP TABLE REPARO CASCADE;
DROP TABLE PERICIA;
DROP TABLE SINISTRO;
DROP TABLE SEGURO;
DROP TABLE OFICINA;
DROP TABLE AUTOMOVEL;
DROP TABLE SEGURADO;
DROP TABLE PERITO;
----------- FIM QUESTAO 9 -----------










