-- Q1
SELECT COUNT(*) FROM EMPLOYEE WHERE sex='F';
-- Q2
SELECT AVG(SALARY) FROM EMPLOYEE WHERE address LIKE '%TX' AND sex='M';
-- Q3
SELECT superssn, COUNT(*) FROM EMPLOYEE GROUP BY superssn; 
-- Q4
SELECT fname AS nome_supervisor, COUNT(*) AS qtd_supervisionados FROM (EMPLOYEE AS E JOIN (SELECT superssn FROM EMPLOYEE) AS S ON E.ssn=S.superssn) GROUP BY fname ORDER BY qtd_supervisionados;
-- Q5
SELECT fname AS nome_supervisor, qtd AS qtd_supervisionados FROM (EMPLOYEE AS E RIGHT OUTER JOIN (SELECT superssn AS ssn, count(*) AS qtd FROM EMPLOYEE GROUP BY (superssn) ORDER BY qtd) AS S ON E.ssn=S.ssn);
-- Q6
SELECT MIN(qtd) AS qtd FROM (SELECT pno, COUNT(*) AS qtd FROM WORKS_ON GROUP BY pno) AS S;
-- Q7
SELECT pno AS num_projeto,qtd AS qtd_func FROM ((SELECT pno,COUNT(*) AS qtd FROM WORKS_ON GROUP BY pno) AS Q JOIN (SELECT MIN(qtd) FROM (SELECT pno,COUNT(*) AS qtd FROM WORKS_ON GROUP BY pno) AS S) AS F ON Q.qtd=F.min);
-- Q8
SELECT pno AS num_proj,AVG(salary) AS media_sal FROM (WORKS_ON AS W JOIN EMPLOYEE AS E ON W.essn=E.ssn) GROUP BY pno;
-- Q9
SELECT num_proj, pname AS proj_name, media_sal FROM (SELECT pno AS num_proj,AVG(salary) AS media_sal FROM (WORKS_ON AS W JOIN EMPLOYEE AS E ON W.essn=E.ssn) GROUP BY pno) AS S JOIN PROJECT ON S.num_proj=PROJECT.pnumber;
-- Q10
SELECT FNAME,SALARY FROM EMPLOYEE LEFT OUTER JOIN WORKS_ON ON SSN=ESSN, (SELECT NUM_PROJ, MEDIA_SAL FROM (SELECT PNO AS NUM_PROJ, AVG(SALARY) AS MEDIA_SAL FROM (WORKS_ON AS W JOIN EMPLOYEE AS E ON W.ESSN=E.SSN) GROUP BY PNO) AS T1 WHERE T1.MEDIA_SAL=(SELECT MAX(MEDIA_SAL) FROM (SELECT PNO AS NUM_PROJ, AVG(SALARY) AS MEDIA_SAL FROM (WORKS_ON AS W JOIN EMPLOYEE AS E ON W.ESSN=E.SSN) GROUP BY PNO) AS T)) AS MAIOR_SAL_PROJ WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEE JOIN WORKS_ON ON SSN=ESSN WHERE PNO=MAIOR_SAL_PROJ.NUM_PROJ) GROUP BY (FNAME, SALARY);
-- Q11
SELECT SSN, COUNT(ESSN) AS QTD_PROJ FROM EMPLOYEE LEFT OUTER JOIN WORKS_ON ON SSN=ESSN GROUP BY SSN ORDER BY QTD_PROJ;
-- Q12
SELECT * FROM (SELECT PNO AS NUM_PROJ,COUNT(SSN) AS QTD_FUNC FROM WORKS_ON RIGHT OUTER JOIN EMPLOYEE ON ESSN=SSN GROUP BY WORKS_ON.PNO) AS TEMP WHERE QTD_FUNC<5 ORDER BY QTD_FUNC;
-- Q13
SELECT DISTINCT(FNAME) FROM EMPLOYEE, DEPENDENT WHERE SSN=ESSN AND SSN IN (SELECT ESSN FROM PROJECT, WORKS_ON WHERE PNUMBER=PNO AND PLOCATION='Sugarland');
-- Q14
SELECT DNAME FROM DEPARTMENT WHERE DNUMBER <> ALL (SELECT DISTINCT(DNUM) FROM PROJECT);
-- Q15
SELECT FNAME, LNAME FROM EMPLOYEE WHERE SSN=(SELECT ESSN FROM (SELECT ESSN,COUNT(PNO) AS TOTAL FROM WORKS_ON WHERE PNO IN (SELECT DISTINCT(PNO) FROM WORKS_ON WHERE ESSN='123456789') GROUP BY ESSN) AS FOO WHERE FOO.ESSN<>'123456789' AND TOTAL = (SELECT COUNT(PNO) FROM WORKS_ON WHERE ESSN='123456789'));
-- Q16
SELECT FNAME,SALARY FROM EMPLOYEE LEFT OUTER JOIN WORKS_ON ON SSN=ESSN, (SELECT NUM_PROJ, MEDIA_SAL FROM (SELECT PNO AS NUM_PROJ, AVG(SALARY) AS MEDIA_SAL FROM (WORKS_ON AS W JOIN EMPLOYEE AS E ON W.ESSN=E.SSN) GROUP BY PNO) AS T1 WHERE T1.MEDIA_SAL=(SELECT MAX(MEDIA_SAL) FROM (SELECT PNO AS NUM_PROJ, AVG(SALARY) AS MEDIA_SAL FROM (WORKS_ON AS W JOIN EMPLOYEE AS E ON W.ESSN=E.SSN) GROUP BY PNO) AS T)) AS MAIOR_SAL_PROJ WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEE JOIN WORKS_ON ON SSN=ESSN WHERE PNO=MAIOR_SAL_PROJ.NUM_PROJ) GROUP BY (FNAME, SALARY);